### ISSUE TITLE
Amounts in configuration file

### ISSUE THREAD

**Issue by nomaster** [chaosdorf/mete#5]
The amounts for deposit and payment should be configured in a file

**Comment by YtvwlD** [comment]
Is this still relevant?

**Comment by YtvwlD** [comment]
How would this be useful?

**Comment by nomaster** [comment]
I thought it would be nice to have the currency and variety of paper money to be configurable. Maybe it's better to make them managable in the web interface as well.

**Comment by YtvwlD** [comment]
So, how would we want to make this configurable? I don't really see this being useful in the web interface. A simple config file perhaps like this could be used:

```yaml
currency:
  name: euro
  symbol: €
amounts:
  - amount: 2
    image: <path>
  - amount: 5
    image: <path>
[…]
```

Do we need more things configurable?
